### ISSUE TITLE
gatsby build ends with error

### ISSUE THREAD

**Issue by bilogic** [CartQL/gatsby-cartql-starter#16]
Hi,

```gatsby develop``` works, albeit with some code warnings.
However, ```gatsby build``` ends with an error.

The output files in ```./public``` works in a browser, however, I can't be sure if there is anything wrong somewhere. Below is the output for ```gatsby build```. Thank you.

```
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 5.635 s
⠀
success Building production JavaScript and CSS bundles - 14.354s
success Rewriting compilation hashes - 0.004s
success run queries - 15.087s - 7/7 0.46/s
success Generating image thumbnails - 14.382s - 40/40 2.78/s
success Building static HTML for pages - 2.000s - 7/7 3.50/s
info Done building in 36.559038499 sec

 ERROR

The above error occurred in the <CLI> component:
    in CLI (created by ConnectedCLI)
    in ConnectedCLI
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.


 ERROR

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'activities' of undefined
    at getGlobalStatus (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\lib\reporter\redux\utils.js:20:54)
    at createPendingActivity (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\lib\reporter\redux\internal-actions.js:108:51)
    at D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\redux\lib\redux.js:483:35
    at prematureEnd (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\lib\reporter\catch-exit-signals.js:37:38)
    at Reporter.panic (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\lib\reporter\reporter.js:71:42)
    at process.<anonymous> (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js:148:21)
    at process.emit (events.js:322:22)
    at processEmit (D:\Users\User\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\signal-exit\index.js:161:32)
    at processEmit [as emit] (S:\gatsby-cartql-starter\node_modules\signal-exit\index.js:161:32)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)

S:\gatsby-cartql-starter>
```

**Comment by notrab** [comment]
Hey @bilogic there is no reference to `activities` in this starter. I imagine this is related to whatever has been added (`yoga-layout-prebuilt`).
